
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async settingsGet() : Promise<AppSettings> {
    return await TAURI_INVOKE("settings_get");
},
/**
 * Whole-snapshot save — the frontend merges its patch and sends everything.
 */
async settingsSave(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_save", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probesList(scope: string) : Promise<Probe[]> {
    return await TAURI_INVOKE("probes_list", { scope });
},
async probesGet(id: string, scope: string) : Promise<Result<Probe, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probes_get", { id, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full-replace semantics, matching stibu's `UpdateCustomerInput`.
 */
async probesSave(body: Probe, scope: string) : Promise<Result<Probe, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probes_save", { body, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test control: make the next save return something else.
 */
async probesHijack(patch: ProbePatch) : Promise<void> {
    await TAURI_INVOKE("probes_hijack", { patch });
},
async probesReset() : Promise<void> {
    await TAURI_INVOKE("probes_reset");
},
/**
 * The paged rig: keyset paging plus a pushed-down search over a corpus small
 * enough to exhaust. This is the deterministic test bed for the collection's
 * search escalation — a 100 cap exhausts the 40-record base and search stays
 * local; a 20 cap leaves it capped and every term pushes down.
 */
async probesPage(search: string, limit: number, cursor: string | null) : Promise<ProbePage> {
    return await TAURI_INVOKE("probes_page", { search, limit, cursor });
},
async editionsList() : Promise<Edition[]> {
    return await TAURI_INVOKE("editions_list");
},
async shelfList() : Promise<ShelfEntry[]> {
    return await TAURI_INVOKE("shelf_list");
},
/**
 * Three-state cycle: none → owned → want → none. Not a record-shaped update,
 * which is why the frontend calls it directly and then refreshes rather than
 * routing it through the collection's write layer.
 */
async shelfToggle(id: string) : Promise<void> {
    await TAURI_INVOKE("shelf_toggle", { id });
},
async libraryReset() : Promise<void> {
    await TAURI_INVOKE("library_reset");
},
async loansList(year: string) : Promise<Loan[]> {
    return await TAURI_INVOKE("loans_list", { year });
},
async loansPage(year: string, limit: number, cursor: string | null) : Promise<Result<LoanPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_page", { year, limit, cursor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loansGet(id: string, year: string) : Promise<Result<Loan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_get", { id, year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The record-shaped edit — the only loan operation that belongs to the
 * collection's write layer.
 */
async loansSave(body: Loan, year: string) : Promise<Result<Loan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_save", { body, year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 1 — soft delete. Returns the record.
 */
async loansReturn(id: string, year: string) : Promise<Result<Loan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_return", { id, year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 2 — hard delete. Drafts only, returns nothing.
 */
async loansCancel(id: string, year: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_cancel", { id, year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 3 — counter-document. Closes the original and issues a REPLACEMENT.
 */
async loansMarkLost(id: string, year: string) : Promise<Result<Loan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_mark_lost", { id, year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 4 — soft, terminal. Returns nothing.
 */
async loansArchive(id: string, year: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_archive", { id, year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The create path — reached by the list header's one forward action.
 */
async loansCreate(year: string) : Promise<Result<Loan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loans_create", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loansReset() : Promise<void> {
    await TAURI_INVOKE("loans_reset");
},
/**
 * A collection of exactly one — archetype E's data.
 */
async prefsList() : Promise<Preferences[]> {
    return await TAURI_INVOKE("prefs_list");
},
async prefsSave(body: Preferences) : Promise<Preferences> {
    return await TAURI_INVOKE("prefs_save", { body });
},
async prefsReset() : Promise<void> {
    await TAURI_INVOKE("prefs_reset");
},
async stressPage(search: string, kind: string, order: string, desc: boolean, limit: number, cursor: string | null) : Promise<EntryPage> {
    return await TAURI_INVOKE("stress_page", { search, kind, order, desc, limit, cursor });
},
async stressGet(id: number) : Promise<Result<Entry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stress_get", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the dataset without asking for a page — lets the UI show the one-off
 * generation cost rather than blaming it on the first query.
 */
async stressWarm() : Promise<number> {
    return await TAURI_INVOKE("stress_warm");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { 
/**
 * Whether first-launch onboarding has been completed or skipped.
 */
onboarding_completed: boolean }
export type Edition = { id: string; work_id: string; work_title: string; author: string; year: number; format: string }
/**
 * A stored row. Owns its strings — see the module note.
 */
export type Entry = { 
/**
 * i32, not i64 — specta refuses i64 at the IPC boundary
 * (`BigIntForbidden`), a JS number cannot represent its range.
 */
id: number; date: string; party: string; kind: string; cents: number }
/**
 * One accumulation step, mirroring the kit's `FetchPage`.
 */
export type EntryPage = { records: Entry[]; cursor: string | null; total: number; done: boolean }
/**
 * `i32`, not `i64`: specta forbids `i64` at the IPC boundary because a JS
 * number cannot represent its full range. Any real backend with a BIGINT money
 * or id column hits the same wall — the fix there is a string, not a wider int.
 */
export type Loan = { id: string; title: string; borrower: string; lent_on: string; due_on: string; status: string; replaced_by: string | null; fine_cents: number; note: string }
/**
 * One accumulation step. Mirrors the kit's `FetchPage`: rows, a continuation
 * token, the matching total, and an explicit end-of-data flag.
 */
export type LoanPage = { records: Loan[]; cursor: string | null; total: number; done: boolean }
export type Preferences = { id: string; display_name: string; default_loan_days: number; fine_per_day_cents: number; preferred_format: string; notes: string }
export type Probe = { id: string; name: string; note: string }
/**
 * One accumulation step over the paged probes. Mirrors the kit's `FetchPage`.
 */
export type ProbePage = { records: Probe[]; cursor: string | null; total: number; done: boolean }
export type ProbePatch = { note: string | null }
export type ShelfEntry = { edition_id: string; state: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
